apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  generation: 5
  labels:
    app: filebeat
  name: filebeat
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - env:
        - name: LOGSTASH_HOSTS
          value: 192.168.209.100:5000
        - name: LOG_LEVEL
          value: info
        - name: CLUSTER_NAME
          value: my_cluster
        - name: FILEBEAT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker-registry.default.svc:5000/openshift/filebeat-kubernetes:v0.4
        imagePullPolicy: IfNotPresent
        name: filebeat
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/containers
          name: varlog
        - mountPath: /var/log/pods
          name: varlogpods
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /var/log/containers
          type: ""
        name: varlog
      - hostPath:
          path: /var/log/pods
          type: ""
        name: varlogpods
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
  templateGeneration: 5
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 5
  updatedNumberScheduled: 1
